### ISSUE TITLE
Connection to the RND 103 through  ethernet 

### ISSUE THREAD

**Issue by Pavan143007** [Mango-kid/py-korad#2]
Hello Mango_Kid,
I did not know how to contact you so I am posting it as issue. 
I cannot seem to connect the device through éthernet to my laptop. Also, there are not many sources on the internet to follow. Please can you just guide to the process of connecting the device to my laptop.

Thank you

**Comment by Mango-kid** [comment]
This is not a great place for this, this is designed for issues with the
code.

To solve your connection issues you will first need to use Korads included
windows application over USB and setup the network. If you have issues
after that please contact Korad
