### ISSUE TITLE
Software for KEL103

### ISSUE THREAD

**Issue by puregame** [Mango-kid/py-korad#4]
Hi there,

I purchased a KEL103 because I found your project. But now their site koradtechnology.com is down and I can't download the software to set up the device on the network.

Do you happen to have a copy of the OEM software?

Thanks

**Comment by oclyke** [comment]
Hope you got this sorted out.... just in case I've hosted a copy here:
https://cdn.subluminal.li/third-party/korad/kel103/factory/cd.zip
